version: '2'
services:
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      # KAFKA_CREATE_TOPICS: "test:4:2"
      KAFKA_ZOOKEEPER_CONNECT: [specified zkhost]:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
